### ISSUE TITLE
Personal use?

### ISSUE THREAD

**Issue by banesullivan** [softwareunderground/brand#1]
Is it okay to print these stickers for **personal use**?

**Comment by filippo82** [comment]
@kwinkunks ?

**Comment by kwinkunks** [comment]
**Yes**

I recommend https://www.stickermule.com/ -- they are very high quality -- or make an account on there, give me the email you use to sign up, and I can enable a direct order for you. If you order them yourself, I usually get 2" diameter for this file: https://github.com/softwareunderground/brand/blob/master/stickers/swung_stickers.png (the magenta line is for Stick Mule's layout, it does not appear on the stickers).

They no longer run the Marketplace, unforch, otherwise I'd put it there.
